// royalguru55@gmail.com
// neon.db 
// postgresql://neondb_owner:P74HyLWhYQFd@ep-lively-bar-a1jb7gfz.ap-southeast-1.aws.neon.tech/neondb?sslmode=require

//connection pooled string from prisma
// DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiOGE1ODk3MDEtNGJjMy00ZGViLTg0ODMtZjM5ZTc0Y2ViZDQwIiwidGVuYW50X2lkIjoiYjJlZDMxZmIzYTE1YWIwMWFiYmY0ZTVjNDM1NDBlNjc0MTQ3NGQ1NDVjNmU1YzVkODNhYjNhZGI3MmI2YjI0MSIsImludGVybmFsX3NlY3JldCI6ImFjN2Q2NzIzLWY5MWItNGVmMi04MTA1LThmMTMxMTNiZDJkMiJ9.aAvAHivcYaWwu6BcdvtxtukgnE28GZyYVHWZpvw0Z0A"